# Generated by Django 4.0.5 on 2022-07-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_alter_cart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='pro.items'),
        ),
    ]
