# Generated by Django 4.0.5 on 2022-07-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_alter_products_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allorder',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allorder',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='pro.order_count'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='pro.buyed'),
        ),
        migrations.AlterField(
            model_name='order_count',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='re_views',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
