# Generated by Django 4.0.5 on 2022-07-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_alter_allorder_cost_alter_allorder_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='desc',
            field=models.TextField(),
        ),
    ]
