# Generated by Django 4.0.5 on 2022-07-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_allorder_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='allorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
